name: Deploy to Staging

on:
  workflow_run:
    workflows: [Zooni CI]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  check_ci_ok:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
          echo 'The triggering CI tests workflow is ok'
          exit 0

  build_and_push_image:
    name: Build and Push Image
    uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
    needs: check_ci_ok
    with:
      repo_name: kade
      commit_id: ${{ github.sha }}
      latest: true

  db_migration_staging:
    name: Staging DB Migration
    uses: zooniverse/ci-cd/.github/workflows/db_migration.yaml@main
    needs: build_and_push_image
    with:
      app_name: kade
      environment: staging
      commit_id: ${{ github.sha }}
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  deploy_staging:
    name: Deploy to Staging
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    needs: [build_and_push_image, db_migration_staging]
    with:
      app_name: kade
      repo_name: kade
      commit_id: ${{ github.sha }}
      environment: staging
    secrets:
      creds: ${{ secrets.AZURE_AKS }}

  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy_staging
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy to Staging / deploy_app
      status: ${{ needs.deploy_staging.result }}
      title: "KaDE API Staging deploy & migration complete"
      title_link: "https://kade-staging.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
